language: python
sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org

python:
  - 3.4
  - 3.5

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh
  - mkdir ~/amostra_files

install:
  - mongo localhost:27017/admin ~/scripts/admin.js
  - conda create -n testenv --yes nose python=$TRAVIS_PYTHON_VERSION pymongo ujson tornado jsonschema pyyaml pytz doct -c lightsource2
  - source activate testenv
  - pip install coveralls codecov mongoquery requests pytest pytest-cov

script:
  - nohup python startup.py --mongo-host localhost --mongo-port 27017 --timezone US/Easternm --database amostra_test --service-port 7770  &
  - py.test -sv --cov=amostra --cov-report term-missing

after_success:
  - coveralls
  - codecov
  - rm -r ~/amostra_files
